title: test

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: mkc1370
    github: mkc1370

permalink: none

google_analytics: G-1N815EC5ZN

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed
